server:
  port: 8080

spring:
  application:
    name: kafka

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 1
      batch-size: 16384
      linger-ms: 5
      properties:
        spring.json.add.type.headers: false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: demo-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 50
      properties:
        spring.json.trusted.packages: "com.demo.kafka.model"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.demo.kafka.model.UserEvent

# Custom application properties
app:
  kafka:
    topic:
      name: base-topic
      partitions: 3
      replication-factor: 1

logging:
  level:
    com.kafka.demo: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  datasource:
    url: jdbc:postgresql://localhost:5432/javaapp
    username: javadev
    password: javadev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect